version: "3.9"
    
services:
  db:
    image: mariadb:11.8
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD_FILE: /run/secrets/db_user_password
      MARIADB_DATABASE: wordpress
      MARIADB_USER: wordpress
      MARIADB_PASSWORD_FILE: /run/secrets/db_user_password
    secrets:
      - db_user_password
      - db_root_user_password
    
  wordpress:
    depends_on:
      - db
    image: wordpress:6.8.1-apache
    volumes:
      - wordpress_data:/var/www/html
      - ./uploads.ini:/usr/local/etc/php/conf.d/uploads.ini # https://www.aptgetlife.co.uk/docker-wordpress-increase-php-max-file-size/
    restart: always
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD_FILE: /run/secrets/db_user_password
      WORDPRESS_DB_NAME: wordpress
    secrets:
      - db_user_password

  caddy:
    image: caddy:2.10.0
    depends_on:
      - wordpress
    restart: always
    environment:
      DOMAIN: ${SERVICE_HOST}
    ports:
      - "${SERVICE_HTTP_PORT}:80"
      - "${SERVICE_HTTPS_PORT}:443"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config  
      
secrets:
  db_root_user_password:
    file: ./credentials/db-root-user-password.txt
  
  db_user_password:
    file: ./credentials/db-user-password.txt

volumes:
  db_data: {}
  wordpress_data: {}
  caddy_data: {}
  caddy_config: {}

